name: validate-schema

on:
  push:
    branches: [ main ]
    
jobs:
  Validate-JSON-Schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # checkout repo content
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Download json validator
        run: wget https://www.itb.ec.europa.eu/json-offline/any/validator.zip
      - name: Extract json validator
        run: unzip validator.zip
      - name: Validate data-item.schema.json through sample (1)
        run: |
         java -jar validator.jar \
           -input $GITHUB_WORKSPACE/descriptions/monopad-ada-1.0/data-item-sample-1.json \
           -schema $GITHUB_WORKSPACE/descriptions/monopad-ada-1.0/data-item.schema.json \
           ; grep -q error report.0.csv ; test $? -ne 0
      - name: Validate data-item.schema.json through sample (2)
        run: |
         java -jar validator.jar \
           -input $GITHUB_WORKSPACE/descriptions/monopad-ada-1.0/data-item-sample-2.json \
           -schema $GITHUB_WORKSPACE/descriptions/monopad-ada-1.0/data-item.schema.json \
           ; grep -q error report.0.csv ; test $? -ne 0
      - name: Validate data-item.schema.json through sample (empty)
        run: |
         java -jar validator.jar \
           -input $GITHUB_WORKSPACE/descriptions/monopad-ada-1.0/data-item-sample-empty.json \
           -schema $GITHUB_WORKSPACE/descriptions/monopad-ada-1.0/data-item.schema.json \
           ; grep -q error report.0.csv ; test $? -ne 0
      - name: Validate data-item.schema.json through sample (invalid)
        run: |
         java -jar validator.jar \
           -input $GITHUB_WORKSPACE/descriptions/monopad-ada-1.0/data-item-sample-invalid.json \
           -schema $GITHUB_WORKSPACE/descriptions/monopad-ada-1.0/data-item.schema.json \
           ; grep -q error report.0.csv ; test $? -eq 0

